{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3e34357a-0d2f-4aff-8b17-0e8a1f48b05a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import dask.array as da\n",
    "import numpy as np\n",
    "from dask.distributed import Client\n",
    "import marineHeatWaves as mhw"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9bb3b483-e150-4a11-bb07-12d6cf07a0c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "client = Client()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "430d797e-4edd-4659-87e7-fecbbead09a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-22 14:41:14,603 - distributed.nanny - WARNING - Worker process still alive after 3.1999986267089846 seconds, killing\n",
      "2023-02-22 14:41:14,604 - distributed.nanny - WARNING - Worker process still alive after 3.1999987792968754 seconds, killing\n",
      "2023-02-22 14:41:14,604 - distributed.nanny - WARNING - Worker process still alive after 3.1999986267089846 seconds, killing\n",
      "2023-02-22 14:41:14,605 - distributed.nanny - WARNING - Worker process still alive after 3.1999989318847657 seconds, killing\n"
     ]
    }
   ],
   "source": [
    "client.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "981b838a-4972-4346-9329-2dc29c06ce13",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7862' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7861' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7875' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7797' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7892' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7799' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7889' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7881' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7895' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7880' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/p8/985fq4dx1356qtcv5dd4zgyr0000gn/T/ipykernel_37987/2231080941.py\", line 11, in <module>\n",
      "    result.compute()\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/dask/base.py\", line 314, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/dask/base.py\", line 599, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 3144, in get\n",
      "    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2313, in gather\n",
      "    return self.sync(\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/utils.py\", line 338, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/utils.py\", line 401, in sync\n",
      "    wait(10)\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/utils.py\", line 390, in wait\n",
      "    return e.wait(timeout)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/threading.py\", line 622, in wait\n",
      "    signaled = self._cond.wait(timeout)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/threading.py\", line 324, in wait\n",
      "    gotit = waiter.acquire(True, timeout)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2057, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 854, in get_records\n",
      "    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/stack_data/core.py\", line 597, in stack_data\n",
      "    yield from collapse_repeated(\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/stack_data/utils.py\", line 83, in collapse_repeated\n",
      "    yield from map(mapper, original_group)\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/stack_data/core.py\", line 587, in mapper\n",
      "    return cls(f, options)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/stack_data/core.py\", line 551, in __init__\n",
      "    self.executing = Source.executing(frame_or_tb)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/executing/executing.py\", line 359, in executing\n",
      "    source = cls.for_frame(frame)\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/executing/executing.py\", line 277, in for_frame\n",
      "    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/executing/executing.py\", line 306, in for_filename\n",
      "    return cls._for_filename_and_lines(filename, tuple(lines))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/executing/executing.py\", line 317, in _for_filename_and_lines\n",
      "    result = source_cache[(filename, lines)] = cls(filename, lines)\n",
      "                                               ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/executing/executing.py\", line 257, in __init__\n",
      "    self.tree = ast.parse(ast_text, filename=filename)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/ast.py\", line 50, in parse\n",
      "    return compile(source, filename, mode, flags,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "SystemError: AST constructor recursion depth mismatch (before=129, after=69)\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7874' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7884' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7872' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7867' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7877' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7866' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7855' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7865' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7848' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7845' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7851' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7837' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7835' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7841' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7825' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7823' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7829' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7813' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7815' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7803' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7806' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7887' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7890' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7894' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7873' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7871' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7860' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7857' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7864' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7847' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7846' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7839' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7836' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7826' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7808' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7885' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7800' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7868' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7854' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7863' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7852' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7844' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7810' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7811' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7816' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7896' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7893' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7824' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7821' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7818' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7830' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7817' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7809' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7843' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7838' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7798' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7883' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7842' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7801' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7888' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7870' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7831' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7827' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7856' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7832' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7882' coro=<Client._gather.<locals>.wait() done, defined at /Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py:2141> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rwegener/miniconda3/envs/chesapeake_mhw/lib/python3.11/site-packages/distributed/client.py\", line 2150, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    }
   ],
   "source": [
    "# Create fake input data\n",
    "lat_size, long_size = 100, 100\n",
    "data = da.random.random_integers(0, 30, size=(1_000, long_size, lat_size), chunks=(-1, 10, 10))  # size = (time, longitude, latitude)\n",
    "time = np.arange(730_000, 731_000)  # time in ordinal days\n",
    "\n",
    "# define a wrapper to rearrange arguments\n",
    "def func1d(arr, time):\n",
    "    return mhw.detect(time, arr)\n",
    "\n",
    "result = da.apply_along_axis(func1d, 0, data, time=time, dtype=data.dtype, shape=(1000,))\n",
    "result.compute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c93abdf8-72f2-4923-a5ca-60407495c2de",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:chesapeake_mhw]",
   "language": "python",
   "name": "conda-env-chesapeake_mhw-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
